## Common Numpy Operations in ML

In [1]:
import numpy as np

In [2]:
# Manipulating the dimensions of an array
data = np.arange(0,10,1)

In [3]:
# 1D array
data.shape

(10,)

In [4]:
# Min/Max values
print(f"Min: {data.min()}")
print(f"Max: {data.max()}")

Min: 0
Max: 9


In [5]:
# Position in array with largest value
print(f"Arg Max: {np.array([3,2,1]).argmax()}")

Arg Max: 0


## 2D arrays, i.e, matrix

In [6]:
data.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [7]:
data2D = data.reshape(2,5)
print("2x5 = 2 rows 5 columns")
print(data2D)

data2D = data.reshape(5,2)
print("5x2 = 5 rows 2 columns")
print(data2D)

2x5 = 2 rows 5 columns
[[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 = 5 rows 2 columns
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [8]:
# Specifying only one dimension
data2D = data.reshape(-1,5)
print("2x5 = 2 rows 5 columns")
print(data2D)

data2D = data.reshape(5,-1)
print("5x2 = 5 rows 2 columns")
print(data2D)

2x5 = 2 rows 5 columns
[[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 = 5 rows 2 columns
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## Higher dimensional arrays, i.e, tensor

In [9]:
data.reshape(-1,2,1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]],

       [[6],
        [7]],

       [[8],
        [9]]])

In [10]:
data.reshape(-1,1,2)

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]],

       [[6, 7]],

       [[8, 9]]])